In [1]:
print("hello")x

hello


In [3]:
print("hyy")

hyy


In [4]:
a=[1,2,3,4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


In [5]:
type(a)

list

In [6]:
import numpy as np

In [7]:
b=np.array(a)

In [8]:
print(b)

[1 2 3 4 5 6]


In [9]:
type(b)

numpy.ndarray

In [10]:
a.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [11]:
b.ndim

1

In [12]:
c=np.array([1.2],[9,4])
c.ndim

TypeError: Field elements must be 2- or 3-tuples, got '9'

In [13]:
c=np.array[[1.2],[9,4]]
c.ndim

TypeError: 'builtin_function_or_method' object is not subscriptable

In [14]:
c=np.array[[1,2],[9,4]]
c.ndim

TypeError: 'builtin_function_or_method' object is not subscriptable

In [15]:
c=np.array([[1.2],[9,4]])
c.ndim

/tmp/ipykernel_6052/3983822994.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[1.2],[9,4]])


1

In [16]:
c=np.array[[1,2],[9,4]]
type(c)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [17]:
c=np.array[[1.2],[3,4]]
type(c)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [18]:
c=np[1,2],[9,4]]
type(c)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [19]:
c=[[1,2],[9,4]]
type(c)

list

In [20]:
d=np.array(c)
print(d)

[[1 2]
 [9 4]]


In [21]:
d.ndim

2

In [22]:
e=np.array(d)
print(e)

[[1 2]
 [9 4]]


In [23]:
x=[[8,9][1,2],[9,4],[6,6]]]
y=np.array(x)


SyntaxError: unmatched ']' (2285823500.py, line 1)

In [24]:
x=[[[8,9][1,2],[9,4],[6,6]]]
y=np.array(x)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_6052/1419326349.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=[[[8,9][1,2],[9,4],[6,6]]]
/tmp/ipykernel_6052/1419326349.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=[[[8,9][1,2],[9,4],[6,6]]]
/tmp/ipykernel_6052/1419326349.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=[[[8,9][1,2],[9,4],[6,6]]]


TypeError: list indices must be integers or slices, not tuple

In [25]:
x=[[[8,9][1,2],[9,4],[6,6]]]
y=np.array(x)
y.ndim

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_6052/428415230.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=[[[8,9][1,2],[9,4],[6,6]]]
/tmp/ipykernel_6052/428415230.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=[[[8,9][1,2],[9,4],[6,6]]]
/tmp/ipykernel_6052/428415230.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=[[[8,9][1,2],[9,4],[6,6]]]


TypeError: list indices must be integers or slices, not tuple

In [26]:
x=[[[8,9],[1,2],[9,4],[6,6]]]
y=np.array(x)
y.ndim


3

In [27]:
print(y)

[[[8 9]
  [1 2]
  [9 4]
  [6 6]]]


In [28]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [29]:
y.shape

(1, 4, 2)

In [30]:
y.dtype

dtype('int64')

In [31]:
y.itemsize

8

In [32]:
y.data

In [33]:
np.zeroes

AttributeError: module 'numpy' has no attribute 'zeroes'

In [34]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros(y.shape)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])